### ISSUE TITLE
What are the requirements for adding frameworks?

### ISSUE THREAD

**Issue by GuutBoy** [rdragos/awesome-mpc#5]
I was just wondering if you have some requirements for frameworks to be acceptable to include?

I ask because there is a bunch of frameworks that comes to mind that are not featured on the list. For example, Viff, Tasty, ObliVM, Wysteria. I was wondering if it was an active choice not to include them? 

Most, if not all, of the mentioned frameworks are probably no longer being maintained, but they are still available.

**Comment by rdragos** [comment]
Hi,

Good question. I thought that it would be good to have a list with actively maintained stuff (or recently developed) rather than enumerating all the existent libraries.

**Comment by GuutBoy** [comment]
I think it a good idea to limit it to actively maintained stuff. I was just wondering if it was a conscious choice.

**Comment by dd23** [comment]
I think the list was created by having people submit their current work at the last TPMPC and that's part of the reason why older frameworks are not listed. 

Anyhow. What about having a separate list of older frameworks, that's clearly marked as "not maintained anymore", or something like that?

**Comment by GuutBoy** [comment]
I think you are referring to to this list: http://www.multipartycomputation.com/mpc-software

Any, it could make sense to list old frameworks for historic reasons. Some of them may still be interesting to use if nothing else but to inspire new work.

**Comment by rdragos** [comment]
@dd23 the idea of the list started before Nigel announced it at TPMPC. As far as I remember it started as a lunch conversation with @GuutBoy .

But yeah, a 'useful but no longer supported' is a useful category...

**Comment by rdragos** [comment]
I guess I have added a corresponding category now, issue can be closed.
