### ISSUE TITLE
add EMP

### ISSUE THREAD

**Issue by wangxiao1254** [rdragos/awesome-mpc#8]
https://github.com/emp-toolkit

**Comment by rdragos** [comment]
Will do!

My only problem is that I am not sure into what category is best fitted - Do you reckon Tools is a better section? - my thought is that there are many useful things you have there but there are some dependencies between them. I haven't dug in the code, please correct me if I am wrong.

**Comment by wangxiao1254** [comment]
EMP-toolkit contains the follow:
- emp-ot, which is a set of OT primitives like libOTe
- emp-sh2pc, semi-honest 2PC, like Obliv-C but without domain specific lang. (We provide circuit library object instead)
- emp-ag2pc, emp-agmpc, emp-m2pc are malicious two-party and multi-party computation protocols. So they are something like SPDZ, TinyLEGO, etc.

Most MPC protocols requires OT, so we have OT in a standalone lib as a dependency to other protocols.

I think just referring to  our main page and treating the whole thing as a framework makes sense to me.

**Comment by rdragos** [comment]
What do you think of the line I have just added?

You can do a pull request if you think something else must be added / removed ;)

**Comment by wangxiao1254** [comment]
Thanks!
